# Digital Ocean App Platform Configuration for ProjectMeats3
name: projectmeats3
region: nyc

databases:
- name: projectmeats-db
  engine: PG
  version: "15"
  num_nodes: 1
  size: basic-xs

services:
- name: api
  source_dir: /backend
  github:
    repo: Meats-Central/ProjectMeats3
    branch: main
    deploy_on_push: true
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  build_command: pip install -r requirements.txt
  run_command: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python -m gunicorn --worker-tmp-dir /dev/shm --workers 2 --timeout 60 --bind 0.0.0.0:8080 projectmeats.wsgi:application
  health_check:
    http_path: /api/v1/health/
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /api
  - path: /admin
  - path: /static
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    type: SECRET
  - key: ALLOWED_HOSTS
    value: "${APP_DOMAIN}"
  - key: INTERNAL_ALLOWED_HOSTS
    value: "10.244.45.4,localhost,127.0.0.1"
  - key: DATABASE_URL
    value: "${projectmeats-db.DATABASE_URL}"
  - key: CORS_ALLOWED_ORIGINS
    value: "https://${APP_DOMAIN}"
  - key: DJANGO_SETTINGS_MODULE
    value: "projectmeats.settings.production"

- name: web
  source_dir: /frontend
  github:
    repo: Meats-Central/ProjectMeats3
    branch: main
    deploy_on_push: true
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: npm ci --production=false && npm run build
  run_command: npx serve -s build -l 3000 -d
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: REACT_APP_API_BASE_URL
    value: "https://${APP_DOMAIN}/api/v1"
  - key: REACT_APP_AI_ASSISTANT_ENABLED
    value: "true"