# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
    ]
