# Generated by Django 4.2.7 on 2025-09-11 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Theme configuration (colors, fonts, logos, etc.)",
                    ),
                ),
                (
                    "feature_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature flag configuration for this tenant",
                    ),
                ),
                (
                    "business_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business-specific settings and preferences",
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Notification preferences and settings",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom field definitions for entities",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Tenant this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Configuration",
                "verbose_name_plural": "Tenant Configurations",
                "db_table": "tenant_configs",
            },
        ),
    ]
