# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="related_customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Related customer if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_contacts",
                to="customers.customer",
            ),
        ),
    ]
