# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("contacts", "0002_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="related_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Related supplier if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_contacts",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
    ]
