# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("purchase_orders", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier for this purchase order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this entity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who last modified this entity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this entity",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "po_number"), name="unique_po_number_per_tenant"
            ),
        ),
    ]
