# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Current status of the entity",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Plant/facility name", max_length=200),
                ),
                (
                    "plant_number",
                    models.CharField(
                        blank=True,
                        help_text="Official plant number (e.g., USDA establishment number)",
                        max_length=50,
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("slaughter", "Slaughter Facility"),
                            ("processing", "Processing Plant"),
                            ("packaging", "Packaging Facility"),
                            ("cold_storage", "Cold Storage"),
                            ("distribution", "Distribution Center"),
                        ],
                        default="processing",
                        help_text="Type of processing plant",
                        max_length=20,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, help_text="Plant manager name", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Plant email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Plant phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="United States", max_length=50
                    ),
                ),
                (
                    "daily_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Daily processing capacity (in pounds or heads)",
                        null=True,
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(
                        default="lbs",
                        help_text="Unit for capacity measurement",
                        max_length=20,
                    ),
                ),
                (
                    "operating_days",
                    models.CharField(
                        blank=True, help_text="Operating days/schedule", max_length=50
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the plant"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who last modified this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this entity belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "db_table": "plants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "certification_type",
                    models.CharField(
                        choices=[
                            ("usda", "USDA Inspected"),
                            ("organic", "USDA Organic"),
                            ("halal", "Halal Certified"),
                            ("kosher", "Kosher Certified"),
                            ("sqf", "SQF Certified"),
                            ("brc", "BRC Certified"),
                            ("haccp", "HACCP Certified"),
                        ],
                        help_text="Type of certification",
                        max_length=20,
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        help_text="Certification number/identifier",
                        max_length=100,
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(
                        blank=True, help_text="Date certification was issued", null=True
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="Date certification expires", null=True
                    ),
                ),
                (
                    "issuing_body",
                    models.CharField(
                        blank=True,
                        help_text="Organization that issued the certification",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who last modified this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="plants.plant",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this entity belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Certification",
                "verbose_name_plural": "Plant Certifications",
                "db_table": "plant_certifications",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="plant",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_plant_name_per_tenant"
            ),
        ),
    ]
