# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts_receivables", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer for this invoice",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who last modified this entity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this entity",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
