# Generated by Django 4.2.7 on 2025-09-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("accounts_receivables", "0002_initial"),
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related purchase order if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this entity belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountsreceivable",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"),
                name="unique_invoice_number_per_tenant",
            ),
        ),
    ]
